api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    formats:
        jsonld: ["application/ld+json"]
        jsonhal: ["application/hal+json"]
        jsonapi: ["application/vnd.api+json"]
        json: ["application/json"]
        xml: ["application/xml", "text/xml"]
        yaml: ["application/x-yaml"]
        csv: ["text/csv"]
        html: ["text/html"]
    patch_formats:
        json: ["application/merge-patch+json"]
        jsonapi: ["application/vnd.api+json"]
    swagger:
        versions: [3, 2]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    graphql:
        enabled: true
        default_ide: "graphiql"
        graphiql:
            enabled: true
        graphql_playground:
            enabled: true
        nesting_separator: _
        collection:
            pagination:
                enabled: true

    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        route_prefix: /api
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
